CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_task VARCHAR(255) NOT NULL,
    descricao TEXT,
    criticidade VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    colaborador_id BIGINT,
    data_criado TIMESTAMP NOT NULL,
    data_fechado TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES colaborador(id)
);